runtime: java11
env: standard
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,postgresql"
handlers:
- url: /.*
  script: this field is required, but ignored
instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 2
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
